name: Acceso a la fortaleza
on: 
  workflow_dispatch: 

jobs:
    acceso-a-la-base:
        runs-on: ubuntu-latest
        steps:

            - name: El agente llega a la fortaleza
              run: |
                echo "Agente ${{ github.actor}} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                ls -la
                echo""
                echo "No hay nada :/"
            - name: "Brayniac desbloquea acceso"
              uses: actions/checkout@v4
            
            - name: "Ver los planes"
              run: |
                echo "Agente ${{ github.actor}} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                ls -la
                echo "Planes!"
                ls planes/
                echo "Villanos"
                ls miembros/
                echo "Inteligencia"
                ls inteligencia/