name: Acceso a la fortaleza
on: push

jobs:
    acceso-a-la-base:
        runs-on: ubuntu-latest
        steps:
            - name: El agente llega a la fortaleza
              run: |
                echo "Agente ${{ github.actor}} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                ls -la
                echo""
                echo "No hay nada :/"