# This is a basic workflow to help you get started with Actions

name: Comunicador de la legión

on:
  workflow_dispatch:
    inputs: 
        villano:
            description: "¿Qué villano envía el mensaje?"
            required: true
            type: choice
            options: 
                - Lex
                - Magento
                - Mystique
        mensaje:
            description: "Mensaje para el consejo"
            required: true
            default: "La misión fue un éxito"
        prioridad:
            description: "Nivel de prioridad"
            required: true
            type: choice
            options: 
                - Normal 
                - Alta
                - Crítica
jobs:
  
  transmitir-mensajes:    
    runs-on: ubuntu-latest  
    steps:
      - name: Instalar el transmisor
        run: sudo apt-get install -y cowsay




      - name: Imprimir variables
        run: |
            echo "============="
            echo "Transmisor: "
            echo "============="
            echo "De: ${{inputs.villano}}"
            echo ""
            echo "Fecha: $(date -u +"%d/%m/%Y - %H:%M UTC")"
            echo "---- Mensaje ----"
            cowsay -f eyes "${{inputs.mensaje}}"
            echo ""
            echo "--- ${{inputs.villano}}"
            echo "..."
            
